language: php
sudo: false

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_script:
  - php vendor/bin/codacycoverage clover coverage.xml

cache:
  directories:
    - $COMPOSER_CACHE_DIR